# Generated by Django 4.2.20 on 2025-04-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("region_name", models.CharField(max_length=50)),
                ("specific_name", models.CharField(max_length=100)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp_st", models.DateTimeField()),
                ("timestamp_end", models.DateTimeField()),
                ("event_emotion", models.CharField(max_length=10)),
                ("weather", models.CharField(max_length=10)),
                ("is_selected_event", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.location",
                    ),
                ),
            ],
        ),
    ]
