# Generated by Django 4.2.20 on 2025-04-30 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("galleries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="galleries.location"
            ),
        ),
    ]
