# Generated by Django 4.2.20 on 2025-04-23 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("diaries", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memo",
            fields=[
                ("memo_id", models.AutoField(primary_key=True, serialize=False)),
                ("memo_content", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="event",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="event",
            name="diary_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="diaries.diary",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="event_emotion",
            field=models.CharField(
                choices=[("TBD", "To Be Determined")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_selected_event",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="location_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="locations.location"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="weather",
            field=models.CharField(
                choices=[("TBD", "To Be Determined")], max_length=20
            ),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AddField(
            model_name="memo",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memos",
                to="events.event",
            ),
        ),
    ]
