# Generated by Django 4.2.20 on 2025-05-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_event_location_id_event_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
