# Generated by Django 4.2.20 on 2025-05-01 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0004_diary_latitude_diary_longitude_alter_diary_emotion"),
        ("events", "0005_event_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="diary_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="diaries.diary",
            ),
        ),
    ]
