# Generated by Django 4.2.20 on 2025-05-01 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_diary_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end_time",
        ),
    ]
