# Generated by Django 4.2.20 on 2025-05-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_remove_event_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_emotion",
        ),
        migrations.AddField(
            model_name="event",
            name="event_emotion_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="event",
            name="weather",
            field=models.CharField(default="sunny", max_length=50),
        ),
    ]
