# Generated by Django 4.2.20 on 2025-05-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_remove_event_event_emotion_event_event_emotion_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_selected_event",
            field=models.BooleanField(default=False),
        ),
    ]
