# Generated by Django 4.2.20 on 2025-05-01 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0004_diary_latitude_diary_longitude_alter_diary_emotion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0009_alter_event_is_selected_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="diary_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="user_id",
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                ("timeline_id", models.AutoField(primary_key=True, serialize=False)),
                ("diary_date", models.DateField()),
                (
                    "diary_id",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="diaries.diary",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("diary_date", "user_id")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="timeline_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.timeline",
            ),
        ),
    ]
