# Generated by Django 4.2.20 on 2025-05-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_remove_event_diary_id_remove_event_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("user_input", "User Input"),
                    ("from_picture", "From Picture"),
                ],
                default="user_input",
                max_length=20,
            ),
        ),
    ]
