# Generated by Django 4.2.20 on 2025-05-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0002_remove_picture_latitude_remove_picture_longitude_and_more"),
        ("events", "0011_alter_keyword_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pictures",
            field=models.ManyToManyField(related_name="events", to="galleries.picture"),
        ),
    ]
