# Generated by Django 4.2.20 on 2025-05-09 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0012_event_pictures"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeline",
            old_name="diary_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="timeline",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="timeline",
            unique_together={("date", "user")},
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_selected_event",
        ),
        migrations.RemoveField(
            model_name="event",
            name="pictures",
        ),
        migrations.RemoveField(
            model_name="event",
            name="timeline_id",
        ),
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="event",
            name="keywords",
            field=models.ManyToManyField(related_name="events", to="events.keyword"),
        ),
        migrations.AddField(
            model_name="event",
            name="memos",
            field=models.ManyToManyField(related_name="events", to="events.memo"),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="timeline",
            name="events",
            field=models.ManyToManyField(related_name="timelines", to="events.event"),
        ),
        migrations.AlterField(
            model_name="memo",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memo_set",
                to="events.event",
            ),
        ),
        migrations.DeleteModel(
            name="EventKeyword",
        ),
        migrations.RemoveField(
            model_name="timeline",
            name="diary_id",
        ),
    ]
