# Generated by Django 4.2.20 on 2025-05-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_rename_diary_date_timeline_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="start_time",
        ),
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
