# Generated by Django 4.2.20 on 2025-05-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_remove_event_start_time_event_time_alter_event_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
    ]
