# Generated by Django 4.2.20 on 2025-05-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_remove_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeline",
            name="event_ids_series",
            field=models.TextField(blank=True, null=True),
        ),
    ]
