# Generated by Django 4.2.20 on 2025-05-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_timeline_event_ids_series"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_id",
            new_name="eventId",
        ),
    ]
