# Generated by Django 4.2.20 on 2025-05-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_rename_event_id_event_eventid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeline",
            name="event_ids_series",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
