# Generated by Django 4.2.20 on 2025-05-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_alter_timeline_event_ids_series"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="eventId",
            new_name="event_id",
        ),
        migrations.AlterField(
            model_name="timeline",
            name="event_ids_series",
            field=models.TextField(blank=True, null=True),
        ),
    ]
