# Generated by Django 4.2.20 on 2025-05-13 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_rename_eventid_event_event_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="event",
            name="memos",
        ),
        migrations.AddField(
            model_name="keyword",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="events.event",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="memo",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memos",
                to="events.event",
            ),
        ),
    ]
