# Generated by Django 4.2.20 on 2025-05-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_remove_event_keywords_remove_event_memos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="source_type",
        ),
    ]
