# Generated by Django 4.2.20 on 2025-05-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_remove_keyword_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="memo_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
