# Generated by Django 4.2.20 on 2025-05-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_event_memo_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="event",
            name="longitude",
        ),
    ]
