# Generated by Django 4.2.20 on 2025-05-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_remove_event_latitude_remove_event_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
