# Generated by Django 4.2.20 on 2025-04-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("region_name", models.CharField(max_length=50)),
                ("specific_name", models.CharField(max_length=100)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                "db_table": "location",
            },
        ),
    ]
