# Generated by Django 4.2.20 on 2025-04-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="location",
            table=None,
        ),
    ]
