# Generated by Django 4.2.20 on 2025-04-24 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchlog",
            old_name="keyword",
            new_name="search_query",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="searched_at",
        ),
        migrations.AddField(
            model_name="searchlog",
            name="search_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="search_type",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
