# Generated by Django 4.2.20 on 2025-04-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_rename_keyword_searchlog_search_query_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchlog",
            name="search_query",
            field=models.TextField(),
        ),
    ]
