# Generated by Django 4.2.20 on 2025-05-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="picture",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="picture",
            name="timestamp",
        ),
        migrations.DeleteModel(
            name="EventPicture",
        ),
    ]
