# Generated by Django 4.2.20 on 2025-04-24 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0005_keyword_rename_content_diary_final_text_and_more"),
        ("galleries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("picture_id", models.AutoField(primary_key=True, serialize=False)),
                ("picture_content_url", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PictureKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("from_picture", "From Picture"),
                            ("from_keyword", "From Keyword"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diaries.keyword",
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galleries.picture",
                    ),
                ),
            ],
            options={
                "unique_together": {("picture", "keyword")},
            },
        ),
        migrations.CreateModel(
            name="EventPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_selected_picture", models.BooleanField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diaries.event"
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galleries.picture",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "picture")},
            },
        ),
    ]
