# Generated by Django 4.2.20 on 2025-04-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("galleries", "0002_picture_picturekeyword_eventpicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpicture",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.event"
            ),
        ),
        migrations.AlterField(
            model_name="picturekeyword",
            name="keyword",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.keyword"
            ),
        ),
    ]
