# Generated by Django 4.2.20 on 2025-05-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0002_remove_picture_latitude_remove_picture_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="picture_caption",
            field=models.TextField(blank=True, null=True),
        ),
    ]
