# Generated by Django 4.2.20 on 2025-05-14 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("galleries", "0003_picture_picture_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="s3_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="picture",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
