# Generated by Django 4.2.20 on 2025-05-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0004_picture_s3_key_picture_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="picture_content_url",
            field=models.URLField(max_length=255),
        ),
    ]
