# Generated by Django 4.2.20 on 2025-05-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0005_alter_picture_picture_content_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="picture_content_url",
        ),
        migrations.AddField(
            model_name="picture",
            name="status",
            field=models.CharField(
                choices=[("temp", "임시 저장"), ("saved", "저장 완료")],
                default="temp",
                help_text="이미지 상태 (임시 저장/저장 완료)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="picture_caption",
            field=models.TextField(blank=True, help_text="이미지 캡션", null=True),
        ),
        migrations.AlterField(
            model_name="picture",
            name="s3_key",
            field=models.CharField(
                blank=True,
                help_text="S3 버킷 내의 파일 경로 (예: temp/filename.jpg 또는 saved/2023/01/filename.jpg)",
                max_length=500,
                null=True,
            ),
        ),
    ]
