# Generated by Django 4.2.20 on 2025-04-30 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                ("diary_id", models.AutoField(primary_key=True, serialize=False)),
                ("diary_date", models.DateField(default=django.utils.timezone.now)),
                ("final_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotion_label", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DiaryKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_selected", models.BooleanField(default=True)),
                ("is_auto_generated", models.BooleanField(default=False)),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diaries.diary"
                    ),
                ),
            ],
            options={
                "verbose_name": "일기 키워드",
                "verbose_name_plural": "일기 키워드 목록",
            },
        ),
    ]
