# Generated by Django 4.2.20 on 2025-04-30 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diaries", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diarykeyword",
            name="keyword",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.keyword"
            ),
        ),
        migrations.AddField(
            model_name="diary",
            name="emotion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diaries.emotion",
            ),
        ),
    ]
