# Generated by Django 4.2.20 on 2025-04-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotion_label", models.CharField(max_length=50)),
            ],
        ),
    ]
