# Generated by Django 4.2.20 on 2025-04-24 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diaries", "0003_emotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp_st", models.DateTimeField()),
                ("timestamp_end", models.DateTimeField()),
                ("event_emotion", models.CharField(max_length=20)),
                ("weather", models.CharField(max_length=20)),
                ("is_selected_event", models.BooleanField()),
                (
                    "diary_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diaries.diary"
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galleries.location",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Memo",
            fields=[
                ("memo_id", models.AutoField(primary_key=True, serialize=False)),
                ("memo_content", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memos",
                        to="diaries.event",
                    ),
                ),
            ],
        ),
    ]
