# Generated by Django 4.2.20 on 2025-04-24 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0004_event_memo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=50)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("user_input", "User Input"),
                            ("from_picture", "From Picture"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="diary",
            old_name="content",
            new_name="final_text",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="timestamp_end",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="timestamp_st",
            new_name="start_time",
        ),
        migrations.AddField(
            model_name="diary",
            name="diary_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="diary",
            name="emotion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diaries.emotion",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_emotion",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="weather",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="EventKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_selected_keyword", models.BooleanField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diaries.event"
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diaries.keyword",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "keyword")},
            },
        ),
        migrations.CreateModel(
            name="DiaryKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_selected", models.BooleanField()),
                ("is_auto_generated", models.BooleanField()),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diaries.diary"
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diaries.keyword",
                    ),
                ),
            ],
            options={
                "unique_together": {("diary", "keyword")},
            },
        ),
    ]
