# Generated by Django 4.2.20 on 2025-05-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0004_diary_latitude_diary_longitude_alter_diary_emotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="camera_target",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diary",
            name="markers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diary",
            name="timeline_sent",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
