# Generated by Django 4.2.20 on 2025-05-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0005_diary_camera_target_diary_markers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
