# Generated by Django 4.2.20 on 2025-04-24 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0005_keyword_rename_content_diary_final_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="diary_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
