# Generated by Django 4.2.20 on 2025-04-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0006_alter_diary_diary_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="diary_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="user_id",
        ),
        migrations.AlterUniqueTogether(
            name="eventkeyword",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="eventkeyword",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventkeyword",
            name="keyword",
        ),
        migrations.RemoveField(
            model_name="memo",
            name="event",
        ),
    ]
