# Generated by Django 4.2.20 on 2025-05-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0006_diary_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="title",
        ),
        migrations.AddField(
            model_name="diary",
            name="keywords",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
