# Generated by Django 4.2.20 on 2025-04-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0007_remove_event_diary_id_remove_event_location_id_and_more"),
        ("galleries", "0003_alter_eventpicture_event_and_more"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diarykeyword",
            name="keyword",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.keyword"
            ),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="EventKeyword",
        ),
        migrations.DeleteModel(
            name="Keyword",
        ),
        migrations.DeleteModel(
            name="Memo",
        ),
    ]
