# Generated by Django 4.2.20 on 2025-04-24 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_agreement"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfilePicture",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("profile_picture_url", models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="agreement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserAlarmSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alarm_type",
                    models.CharField(
                        choices=[
                            ("daily_summary", "Daily Summary"),
                            ("writing_reminder", "Writing Reminder"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("alarm_time", models.TimeField()),
                ("repeat_days", models.CharField(max_length=27)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
