# Generated by Django 4.2.20 on 2025-04-24 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofilepicture_agreement_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="user_name",
        ),
        migrations.AddField(
            model_name="user",
            name="joined_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
